---
html_document: default
author: "Wei"
date: '2024-09-25'
output:
pdf_document: default
title: "receiver operating characteristic curve (ROC curve)"
---

# 1. loading library and function
```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(ROCR))
suppressPackageStartupMessages(library(pROC))
suppressPackageStartupMessages(library(caret))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(openxlsx))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(stringr))
options(dplyr.summarise.inform = FALSE)

```

# 2. loading data
```{r}
IVD_data <- read.xlsx("/Users/xuewei/ZxProjects/20240408_GC_cfDNA/202409/32_AUC/Top100_features/Internal_val.xlsx", sheet = 1, skipEmptyRows = FALSE, colNames = TRUE)
colnames(IVD_data)<-c("predicted", "predicted_prob", "actual", "Sample")

write.xlsx(IVD_data, "GC_02_IVD_data_20240925.xlsx")
# write.table(IVD_data, file="GC_02_IVD_data_20240925.txt", sep = "\t", quote=F, row.names = F, col.names = T)

```

# 3. data processed
## 3.1 calculate Accuracy, AUC, PPV, NPV, Sensitivity and Specificity
```{r}
# 将 predicted 和 actual 转换为因子并使用相同的水平
IVD_data$predicted <- factor(IVD_data$predicted, levels = c(0, 1))
IVD_data$actual <- factor(IVD_data$actual, levels = c(1, 0))

# 计算混淆矩阵
conf_matrix <- confusionMatrix(IVD_data$predicted, IVD_data$actual)

# 计算准确率
accuracy <- conf_matrix$overall['Accuracy']

# 计算AUC
auc <- roc(IVD_data$actual, IVD_data$predicted_prob)$auc

# 计算阳性预测值（PPV）
ppv <- conf_matrix$byClass['Pos Pred Value']

# 计算阴性预测值（NPV）
npv <- conf_matrix$byClass['Neg Pred Value']

# 计算敏感性（Sensitivity）
sensitivity <- conf_matrix$byClass['Sensitivity']

# 计算特异性（Specificity）
specificity <- conf_matrix$byClass['Specificity']

# 打印结果
print(paste("Accuracy:", round(accuracy, 3)))
print(paste("AUC:", round(auc, 3)))
print(paste("PPV:", round(ppv, 3)))
print(paste("NPV:", round(npv, 3)))
print(paste("Sensitivity:", round(sensitivity, 3)))
print(paste("Specificity:", round(specificity, 3)))

```

## 3.2 AUC 95% CI
```{r}
# 将 predicted 和 actual 转换为因子并使用相同的水平
IVD_data$predicted <- factor(IVD_data$predicted, levels = c(0, 1))
IVD_data$actual <- factor(IVD_data$actual, levels = c(1, 0))

# 计算AUC和95%置信区间
roc_obj <- roc(IVD_data$actual, IVD_data$predicted_prob)
auc_value <- auc(roc_obj)
ci_value <- ci.auc(roc_obj)

# 打印结果
print(paste("AUC:", round(auc_value, 3)))
print(paste("95% CI:", round(ci_value[1], 3), "-", round(ci_value[3], 3)))

```

## 3.3 ROC
```{r}
# 创建ROCR预测对象
pred <- prediction(IVD_data$predicted_prob, IVD_data$actual)

# 计算AUC
perf_auc <- performance(pred, "auc")
auc <- as.numeric(performance(pred, "auc")@y.values)
slotNames(perf_auc)

# 创建ROC曲线
perf_roc <- performance(pred, measure = "tpr", x.measure = "fpr")

# tibble(x = perf_roc@x.values[[1]], y = perf_roc@y.values[[1]]) %>%
#   ggplot(aes(x = x, y = y)) + geom_line()

# Non-GC and GC count
count <- table(IVD_data$actual)

pdf('20240925_02_Internal_Validation_Dataset_ROC_v1.pdf', width = 8, height = 6)
tibble(x=perf_roc@x.values[[1]], y=perf_roc@y.values[[1]]) %>%
ggplot(aes(x=x, y=y)) + 
  geom_line(aes(color=cut(y, c(-1,0.5,0.7,0.9,1))), linewidth=2) +
  geom_point(aes(color=cut(y, c(-1,0.5,0.7,0.9,1))), size = 3) +
  theme_bw()+
  labs(color="TPR", x="False Positive Rate", y="True Positive Rate", fill = "CV", title = "") + #  (x: 1-Specificity, y: Sensitivity)  scale_color_brewer(palette = "Blues") + 
  scale_color_brewer(palette = "Blues") + 
  theme(legend.position = "bottom",
        legend.title = element_text(face = "bold"),
        legend.text = element_text(size = 15),
        axis.title = element_text(face = "bold"))+
  geom_text(aes(x=1, y=0, 
                label=paste0("AUC: ", 
                             perf_auc@y.values[[1]] %>% 
                               round(3),
                             " (",
                             round(ci_value[1], 3),
                             "-",
                             round(ci_value[3], 3),
                             ")"
                             )), 
            hjust="right", vjust="bottom", size=6)+
  geom_text(aes(x=1, y=0.08, 
                label=paste0("GC: ", count[1])), 
            hjust="right", vjust="bottom", size=6)+
  geom_text(aes(x=1, y=0.16, 
                label=paste0("Non-GC: ", count[2])),
            hjust="right", vjust="bottom", size=6)+
  theme(axis.text.x = element_text(face="bold", color="black", size=20),
        axis.text.y = element_text(face="bold", color="black", size=20),
        axis.title.x = element_text(face="bold", color="black", size=20),
        axis.title.y = element_text(face="bold",color="black", size=20))
dev.off()

```


## 3.4 Confusion Matrix heatmap
```{r}
conf_matrix_df <- as.data.frame(conf_matrix$table)

conf_matrix_df$Prediction <- factor(conf_matrix_df$Prediction, levels = c("0", "1"))

pdf('20240925_02_Internal_Validation_Dataset_Heatmap_v1.pdf', width = 8, height = 6)
ggplot(data = conf_matrix_df, aes(x = Prediction, y = Reference)) +
  geom_tile(aes(fill = Freq), color = "#FFFFFF") +
  geom_text(aes(label = Freq), vjust = 1, size = 10) + # 调整数字的大小为15
  scale_fill_gradient(low = "#FFFFFF", high = "#1a7fe6") +
  theme_minimal() +
  labs(title = "Internal Validation Dataset", x = "Predicted", y = "Actual") +
  scale_x_discrete(labels=c("0"="Non-GC", "1"="GC")) +
  scale_y_discrete(labels=c("0"="Non-GC", "1"="GC")) +
  theme(legend.position = "right",
        legend.title = element_text(face = "bold", size = 15),
        legend.text = element_text(size = 15),
        axis.title = element_text(face = "bold", size = 20),  # 调整轴标题字号
        axis.text.x = element_text(face = "bold", color = "black", size = 20),  # 调整x轴标签字号
        axis.text.y = element_text(face = "bold", color = "black", size = 20),  # 调整y轴标签字号
        plot.title = element_text(face = "bold", color = "black", size = 20))  # 调整图标题字号

dev.off()

```

