---
html_document: default
author: "Wei"
date: '2024-09-26'
output:
  html_document:
    df_print: paged
title: "receiver operating characteristic curve (ROC curve)"
---

# 1. loading library and function
```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(ROCR))
suppressPackageStartupMessages(library(pROC))
suppressPackageStartupMessages(library(caret))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(ggbeeswarm))
suppressPackageStartupMessages(library(pacman))
pacman::p_load(tidyverse,ggpubr,rstatix,ggsci,ggsignif,reshape2)
suppressPackageStartupMessages(library(openxlsx))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(stringr))
options(dplyr.summarise.inform = FALSE)

```


# 2. loading data
```{r}
Clinical <- read_rds("/Users/xuewei/ZxProjects/20240408_GC_cfDNA/202409/31_Clinical_information/GC_Clinical_info_20240925.rds")

data_feature <- read.xlsx("/Users/xuewei/ZxProjects/20240408_GC_cfDNA/00_backup/20240618-all-features.xlsx", sheet = 1, skipEmptyRows = FALSE, colNames = TRUE)
colnames(data_feature)[colnames(data_feature)=="GCID"] <- "Sample"

cv1 <- read.xlsx("/Users/xuewei/ZxProjects/20240408_GC_cfDNA/202409/32_AUC/Top100_features/cv1.xlsx", sheet = 1, skipEmptyRows = FALSE, colNames = TRUE)
colnames(cv1)<-c("predicted", "predicted_prob", "actual", "Sample")
cv2 <- read.xlsx("/Users/xuewei/ZxProjects/20240408_GC_cfDNA/202409/32_AUC/Top100_features/cv2.xlsx", sheet = 1, skipEmptyRows = FALSE, colNames = TRUE)
colnames(cv2)<-c("predicted", "predicted_prob", "actual", "Sample")
cv3 <- read.xlsx("/Users/xuewei/ZxProjects/20240408_GC_cfDNA/202409/32_AUC/Top100_features/cv3.xlsx", sheet = 1, skipEmptyRows = FALSE, colNames = TRUE)
colnames(cv3)<-c("predicted", "predicted_prob", "actual", "Sample")
cv4 <- read.xlsx("/Users/xuewei/ZxProjects/20240408_GC_cfDNA/202409/32_AUC/Top100_features/cv4.xlsx", sheet = 1, skipEmptyRows = FALSE, colNames = TRUE)
colnames(cv4)<-c("predicted", "predicted_prob", "actual", "Sample")
cv5 <- read.xlsx("/Users/xuewei/ZxProjects/20240408_GC_cfDNA/202409/32_AUC/Top100_features/cv5.xlsx", sheet = 1, skipEmptyRows = FALSE, colNames = TRUE)
colnames(cv5)<-c("predicted", "predicted_prob", "actual", "Sample")
cv6 <- read.xlsx("/Users/xuewei/ZxProjects/20240408_GC_cfDNA/202409/32_AUC/Top100_features/cv6.xlsx", sheet = 1, skipEmptyRows = FALSE, colNames = TRUE)
colnames(cv6)<-c("predicted", "predicted_prob", "actual", "Sample")
cv7 <- read.xlsx("/Users/xuewei/ZxProjects/20240408_GC_cfDNA/202409/32_AUC/Top100_features/cv7.xlsx", sheet = 1, skipEmptyRows = FALSE, colNames = TRUE)
colnames(cv7)<-c("predicted", "predicted_prob", "actual", "Sample")
cv8 <- read.xlsx("/Users/xuewei/ZxProjects/20240408_GC_cfDNA/202409/32_AUC/Top100_features/cv8.xlsx", sheet = 1, skipEmptyRows = FALSE, colNames = TRUE)
colnames(cv8)<-c("predicted", "predicted_prob", "actual", "Sample")
cv9 <- read.xlsx("/Users/xuewei/ZxProjects/20240408_GC_cfDNA/202409/32_AUC/Top100_features/cv9.xlsx", sheet = 1, skipEmptyRows = FALSE, colNames = TRUE)
colnames(cv9)<-c("predicted", "predicted_prob", "actual", "Sample")
cv10 <- read.xlsx("/Users/xuewei/ZxProjects/20240408_GC_cfDNA/202409/32_AUC/Top100_features/cv10.xlsx", sheet = 1, skipEmptyRows = FALSE, colNames = TRUE)
colnames(cv10)<-c("predicted", "predicted_prob", "actual", "Sample")
Training_dataset <- bind_rows(cv1, cv2, cv3, cv4, cv5, cv6, cv7, cv8, cv9, cv10)

IVD_data <- read.xlsx("/Users/xuewei/ZxProjects/20240408_GC_cfDNA/202409/32_AUC/Top100_features/Internal_val.xlsx", sheet = 1, skipEmptyRows = FALSE, colNames = TRUE)
colnames(IVD_data) <- c("predicted", "predicted_prob", "actual", "Sample")
EVD_data <- read.xlsx("/Users/xuewei/ZxProjects/20240408_GC_cfDNA/202409/32_AUC/Top100_features/External_val.xlsx", sheet = 1, skipEmptyRows = FALSE, colNames = TRUE)
colnames(EVD_data) <- c("predicted", "predicted_prob", "actual", "Sample")
join_data <- bind_rows(Training_dataset, IVD_data, EVD_data) %>% 
  distinct()

```


# 3. data processed
## 3.1 join
```{r}
join_data_Clinical <- join_data %>% 
  left_join(Clinical, by = c("Sample" = "Sample")) %>% 
  dplyr::mutate(Group_predicted = case_when(predicted == 0 ~ "Non-GC",
                                            predicted == 1 ~ "GC",
                                  )) %>% 
  distinct()

join_data_feature <- join_data_Clinical %>%
  left_join(data_feature, by = c("Sample" = "Sample")) %>%
  distinct()

```


# 10. Griffin
## 10.1 colname
```{r}
data_colname <- data.frame(
  Feature = c("F531", "F532", "F533", "F534", "F535", "F536", "F537", "F538", "F539", "F540",
              "F541", "F542", "F543", "F544", "F545", "F546", "F547", "F548", "F549", "F550",
              "F551", "F552", "F553", "F554", "F555", "F556", "F557", "F558", "F559", "F560",
              "F561", "F562", "F563", "F564", "F565", "F566", "F567", "F568", "F569", "F570",
              "F571", "F572", "F573", "F574", "F575", "F576", "F577", "F578", "F579", "F580",
              "F581", "F582", "F583", "F584", "F585", "F586", "F587", "F588", "F589", "F590",
              "F591", "F592", "F593", "F594", "F595", "F596", "F597", "F598", "F599", "F600",
              "F601", "F602", "F603", "F604", "F605", "F606", "F607", "F608", "F609", "F610",
              "F611", "F612", "F613", "F614", "F615", "F616", "F617", "F618", "F619", "F620",
              "F621", "F622", "F623", "F624", "F625", "F626", "F627", "F628", "F629", "F630",
              "F631", "F632", "F633", "F634", "F635", "F636", "F637", "F638", "F639", "F640",
              "F641", "F642", "F643", "F644", "F645", "F646", "F647", "F648", "F649", "F650",
              "F651", "F652", "F653", "F654", "F655", "F656", "F657", "F658", "F659", "F660",
              "F661", "F662", "F663", "F664", "F665", "F666", "F667"),
  Location = c(-990, -975, -960, -945, -930, -915, -900, -885, -870, -855, -840, -825, -810,
               -795, -780, -765, -750, -735, -720, -705, -690, -675, -660, -645, -630, -615,
               -600, -585, -570, -555, -540, -525, -510, -495, -480, -465, -450, -435, -420,
               -405, -390, -375, -360, -345, -330, -315, -300, -285, -270, -255, -240, -225,
               -210, -195, -180, -165, -150, -135, -120, -105, -90, -75, -60, -45, -30, -15,
               0, 15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, 195, 210, 225, 240,
               255, 270, 285, 300, 315, 330, 345, 360, 375, 390, 405, 420, 435, 450, 465, 480,
               495, 510, 525, 540, 555, 570, 585, 600, 615, 630, 645, 660, 675, 690, 705, 720,
               735, 750, 765, 780, 795, 810, 825, 840, 855, 870, 885, 900, 915, 930, 945, 960,
               975, "mean_reads_per_bp_in_normalization_window", "mean_reads_per_bp_in_saved_window",
               "mean_coverage", "central_coverage", "amplitude")
)

# write.table(data_colname, "data_colname.txt", sep = "\t", row.names = F)

```

## 10.2 data_Griffin
```{r}
# join_data_feature %>%
#   group_by(OS_time) %>%
#   summarise(count = n())

data_Griffin_Loc <- join_data_feature %>% 
  dplyr::select(Group_predicted, F531:F667)
data_Griffin_Loc2 <- data_Griffin_Loc %>% 
  rownames_to_column(var = "ID")
data_Griffin_Loc3 <- as.data.frame(data.table::transpose(data_Griffin_Loc2, keep.names = "ID", make.names = 1))
  
# join colname and Feature
join_Griffin_Loc3_colname <- left_join(data_Griffin_Loc3, data_colname, by = c("ID" = "Feature"))
# 修改第一行最后一列的值
join_Griffin_Loc3_colname[1, ncol(join_Griffin_Loc3_colname)] <- "Location"
# transpose colname and Feature
join_Griffin_Loc3_colname <- as.data.frame(data.table::transpose(join_Griffin_Loc3_colname, keep.names = "ID", make.names = 1))
join_Griffin_Loc3_colname2 <- join_Griffin_Loc3_colname %>% 
  column_to_rownames(var = "ID")

# 将最后一行的值设置为列名
colnames(join_Griffin_Loc3_colname2) <- as.character(join_Griffin_Loc3_colname2[nrow(join_Griffin_Loc3_colname2), ])
# 删除最后一行
join_Griffin_Loc3_colname2 <- join_Griffin_Loc3_colname2[-nrow(join_Griffin_Loc3_colname2), ]

# write.table(join_Griffin_Loc3_colname2, "join_Griffin_Location.txt", sep = "\t", row.names = F)

```

## 10.3 plot geom_ribbon
```{r}
# 转换数据框结构
data_long <- pivot_longer(join_Griffin_Loc3_colname2, cols = `-990`:`975`, names_to = "Position", values_to = "Value")

data_long$Position <- as.numeric(gsub("X", "", data_long$Position))
data_long$Value <- as.numeric(gsub("X", "", data_long$Value))

# 计算每个位置的均值和标准误
summary_data <- data_long %>% 
  group_by(Position, Location) %>%
  summarise(Mean = mean(Value), SD = sd(Value), Count = n()) %>%
  mutate(SE = SD / sqrt(Count), Lower = Mean - 1.96 * SE, Upper = Mean + 1.96 * SE)

summary_data$Location=factor(summary_data$Location, levels=c('Non-GC', 'GC'))

# 绘制图形
pdf("20240926_cfDNA_05_Griffin_geom_ribbon_v1.pdf", height=6, width=8)
ggplot(summary_data, aes(x = Position, y = Mean, group = Location, color = Location)) +
  geom_line() +
  geom_ribbon(aes(ymin = Lower, ymax = Upper, fill = Location), alpha = 0.4) +
  scale_color_manual(values = c("Non-GC" = "#007fff", "GC" = "#ff8033")) +
  scale_fill_manual(values = c("Non-GC" = "#007fff", "GC" = "#ff8033")) +
  labs(x = "Distance", 
       y = "Normalized Coverage", 
       title = "") +
  theme_minimal() +
  # theme(legend.position = "NA") +
  theme(panel.grid = element_blank(), 
        axis.title = element_text(size = 15),
        strip.text = element_text(size = 15)) +
  theme(plot.title = element_text(face = "bold", color = "black", size = 15, hjust = 0.5)) +
  theme(axis.line = element_line(linewidth = 0.5, colour = "black")) +
  theme(axis.ticks = element_line(linewidth = 0.5, colour = "black"), axis.ticks.length = unit(0.5, "lines")) +
  theme(axis.text.x = element_text(face = "bold", color = "black", size = 15),
        axis.text.y = element_text(face = "bold", color = "black", size = 15),
        axis.title.x = element_text(face = "bold", color = "black", size = 15),
        axis.title.y = element_text(face = "bold", color = "black", size = 15))
dev.off()

```


# 11. mean_coverage
```{r}
join_Griffin_Loc3_colname2$mean_coverage <- as.numeric(join_Griffin_Loc3_colname2$mean_coverage)

summary(join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="Non-GC",]$mean_coverage)
summary(join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="GC",]$mean_coverage)
p <- wilcox.test(join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="Non-GC",]$mean_coverage, join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="GC",]$mean_coverage)
p$p.value

join_mean_coverage <- data.frame(join_Griffin_Loc3_colname2) %>%
  select(Location, mean_coverage)

join_mean_coverage$Location=factor(join_mean_coverage$Location, levels=c('Non-GC', 'GC'))

pdf("20240926_cfDNA_06_mean_coverage_boxplot_v1.pdf", height=5.5, width=5.5)
ggplot(join_mean_coverage, aes(x = Location, y = mean_coverage, fill = factor(Location), color = factor(Location))) +
  # geom_boxplot(width = 0.3, size = 1) +
  geom_violin(width = 0.45, linewidth = 1) +
  geom_quasirandom(width = 0.1, varwidth = TRUE, cex = 2, method = "quasirandom") +
  scale_y_continuous(expand = ggplot2::expansion(mult = c(0.1, 0.1))) +
  geom_signif(comparisons = list(c("Non-GC", "GC")),
              map_signif_level = T,
              textsize = 8,
              test = "wilcox.test",
              step_increase = 0.1,
              color = "#000000")+
  annotate("text", x = 1.39, y = median(join_mean_coverage[join_mean_coverage$Location == "Non-GC", ]$mean_coverage), label = sprintf("%0.3f", median(join_mean_coverage[join_mean_coverage$Location == "Non-GC", ]$mean_coverage)), color = "#000000", size = 6) +
  annotate("text", x = 2.35, y = median(join_mean_coverage[join_mean_coverage$Location == "GC", ]$mean_coverage), label = sprintf("%0.3f", median(join_mean_coverage[join_mean_coverage$Location == "GC", ]$mean_coverage)), color = "#000000", size = 6) +
  theme_classic() +
  theme(legend.position = "NA") +
  scale_fill_manual(values = c("#FFFFFF", "#FFFFFF")) +
  scale_color_manual(values = c("#007fff", "#ff8033")) +
  labs(x = "", y = "Mean Coverage", title = "", fill = "") +
  theme(panel.grid = element_blank(), axis.title = element_text(size = 15)) +
  theme(plot.title = element_text(face = "bold", color = "black", size = 15, hjust = 0.5)) +
  theme(axis.line = element_line(linewidth = 0.5, colour = "black")) +
  theme(axis.ticks = element_line(linewidth = 0.5, colour = "black"), axis.ticks.length = unit(0.5, "lines")) +
  theme(axis.text.x = element_text(face = "bold", color = "black", size = 15),
        axis.text.y = element_text(face = "bold", color = "black", size = 15),
        axis.title.x = element_text(face = "bold", color = "black", size = 15),
        axis.title.y = element_text(face = "bold", color = "black", size = 15))
dev.off()

```


# 12. central_coverage
```{r}
join_Griffin_Loc3_colname2$central_coverage <- as.numeric(join_Griffin_Loc3_colname2$central_coverage)

summary(join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="Non-GC",]$central_coverage)
summary(join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="GC",]$central_coverage)
# p <- wilcox.test(join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="Non-GC",]$predicted_prob,join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="Low",]$predicted_prob)
# p$p.value
# p <- wilcox.test(join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="Non-GC",]$predicted_prob,join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="Mid",]$predicted_prob)
# p$p.value
p <- wilcox.test(join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="Non-GC",]$central_coverage, join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="GC",]$central_coverage)
p$p.value

boxplot_central_coverage <- data.frame(join_Griffin_Loc3_colname2) %>%
  select(Location, central_coverage)

boxplot_central_coverage$Location=factor(boxplot_central_coverage$Location, levels=c('Non-GC', 'GC'))

pdf("20240926_cfDNA_07_central_coverage_boxplot_v1.pdf", height=5.5, width=5.5)
ggplot(boxplot_central_coverage, aes(x = Location, y = central_coverage, fill = factor(Location), color = factor(Location))) +
  # geom_boxplot(width = 0.3, size = 1) +
  geom_violin(width = 0.45, linewidth = 1) +
  geom_quasirandom(width = 0.1, varwidth = TRUE, cex = 2, method = "quasirandom") +
  scale_y_continuous(expand = ggplot2::expansion(mult = c(0.1, 0.1))) +
  geom_signif(comparisons = list(c("Non-GC", "GC")),
              map_signif_level = T,
              textsize = 8,
              test = "wilcox.test",
              step_increase = 0.1,
              color = "#000000")+
  annotate("text", x = 1.29, y = median(boxplot_central_coverage[boxplot_central_coverage$Location == "Non-GC", ]$central_coverage), label = sprintf("%0.3f", median(boxplot_central_coverage[boxplot_central_coverage$Location == "Non-GC", ]$central_coverage)), color = "#000000", size = 6) +
  annotate("text", x = 2.38, y = median(boxplot_central_coverage[boxplot_central_coverage$Location == "GC", ]$central_coverage), label = sprintf("%0.3f", median(boxplot_central_coverage[boxplot_central_coverage$Location == "GC", ]$central_coverage)), color = "#000000", size = 6) +
  theme_classic() +
  theme(legend.position = "NA") +
  scale_fill_manual(values = c("#FFFFFF", "#FFFFFF")) +
  scale_color_manual(values = c("#007fff", "#ff8033")) +
  labs(x = "", y = "Central Coverage", title = "", fill = "") +
  theme(panel.grid = element_blank(), axis.title = element_text(size = 15)) +
  theme(plot.title = element_text(face = "bold", color = "black", size = 15, hjust = 0.5)) +
  theme(axis.line = element_line(linewidth = 0.5, colour = "black")) +
  theme(axis.ticks = element_line(linewidth = 0.5, colour = "black"), axis.ticks.length = unit(0.5, "lines")) +
  theme(axis.text.x = element_text(face = "bold", color = "black", size = 15),
        axis.text.y = element_text(face = "bold", color = "black", size = 15),
        axis.title.x = element_text(face = "bold", color = "black", size = 15),
        axis.title.y = element_text(face = "bold", color = "black", size = 15))
dev.off()

```

# 13. amplitude
```{r}
join_Griffin_Loc3_colname2$amplitude <- as.numeric(join_Griffin_Loc3_colname2$amplitude)

summary(join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="Non-GC",]$boxplot_amplitude)
summary(join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="GC",]$boxplot_amplitude)
# p <- wilcox.test(join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="Non-GC",]$predicted_prob,join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="Low",]$predicted_prob)
# p$p.value
# p <- wilcox.test(join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="Non-GC",]$predicted_prob,join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="Mid",]$predicted_prob)
# p$p.value
p <- wilcox.test(join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="Non-GC",]$amplitude, join_Griffin_Loc3_colname2[join_Griffin_Loc3_colname2$Location=="GC",]$amplitude)
p$p.value

boxplot_amplitude <- data.frame(join_Griffin_Loc3_colname2) %>%
  select(Location, amplitude)

boxplot_amplitude$Location=factor(boxplot_amplitude$Location, levels=c('Non-GC', 'GC'))

pdf("20240926_cfDNA_08_amplitude_boxplot_v1.pdf", height=5.5, width=5.5)
ggplot(boxplot_amplitude, aes(x = Location, y = amplitude, fill = factor(Location), color = factor(Location))) +
  # geom_boxplot(width = 0.3, size = 1) +
  geom_violin(width = 0.45, linewidth = 1) +
  geom_quasirandom(width = 0.1, varwidth = TRUE, cex = 2, method = "quasirandom") +
  scale_y_continuous(expand = ggplot2::expansion(mult = c(0.1, 0.1))) +
  geom_signif(comparisons = list(c("Non-GC", "GC")),
              map_signif_level = T,
              textsize = 8,
              test = "wilcox.test",
              step_increase = 0.1,
              color = "#000000")+
  annotate("text", x = 1.41, y = median(boxplot_amplitude[boxplot_amplitude$Location == "Non-GC", ]$amplitude), label = sprintf("%0.3f", median(boxplot_amplitude[boxplot_amplitude$Location == "Non-GC", ]$amplitude)), color = "#000000", size = 6) +
  annotate("text", x = 2.41, y = median(boxplot_amplitude[boxplot_amplitude$Location == "GC", ]$amplitude), label = sprintf("%0.3f", median(boxplot_amplitude[boxplot_amplitude$Location == "GC", ]$amplitude)), color = "#000000", size = 6) +
  theme_classic() +
  theme(legend.position = "NA") +
  scale_fill_manual(values = c("#FFFFFF", "#FFFFFF")) +
  scale_color_manual(values = c("#007fff", "#ff8033")) +
  labs(x = "", y = "Amplitude", title = "", fill = "") +
  theme(panel.grid = element_blank(), axis.title = element_text(size = 15)) +
  theme(plot.title = element_text(face = "bold", color = "black", size = 15, hjust = 0.5)) +
  theme(axis.line = element_line(linewidth = 0.5, colour = "black")) +
  theme(axis.ticks = element_line(linewidth = 0.5, colour = "black"), axis.ticks.length = unit(0.5, "lines")) +
  theme(axis.text.x = element_text(face = "bold", color = "black", size = 15),
        axis.text.y = element_text(face = "bold", color = "black", size = 15),
        axis.title.x = element_text(face = "bold", color = "black", size = 15),
        axis.title.y = element_text(face = "bold", color = "black", size = 15))
dev.off()

```

